# Generated by Django 4.1.1 on 2022-09-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBP', models.IntegerField()),
                ('DAP', models.IntegerField()),
                ('TMF', models.IntegerField()),
            ],
        ),
    ]
